/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.jmoordbcore.capitulo13.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Embedded;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.Referenced;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;
import com.jmoordb.core.annotation.enumerations.JakartaSource;
import com.jmoordb.core.annotation.enumerations.TypeReferenced;

/**
 *
 * @author avbravo
 */
@Entity(jakartaSource = JakartaSource.JAVAEE_LEGACY)
public class Animal {
 @Id(autogeneratedActive = AutogeneratedActive.ON)
 private Long idanimal;
 @Column
 private String animal;
 
 @Embedded
 private Especie especie;
 
 @Referenced(from = "grupo",localField = "idgrupo",typeReferenced = TypeReferenced.REFERENCED)
 private Grupo grupo;

 
 
 
    public Especie getEspecie() {
        return especie;
    }

    public void setEspecie(Especie especie) {
        this.especie = especie;
    }

    public Grupo getGrupo() {
        return grupo;
    }

    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }

    public Animal() {
    }

    public Animal(Long idanimal, String animal, Especie especie, Grupo grupo) {
        this.idanimal = idanimal;
        this.animal = animal;
        this.especie = especie;
        this.grupo = grupo;
    }

    
    
    
    
    public Animal(Long idanimal, String animal) {
        this.idanimal = idanimal;
        this.animal = animal;
    }

    public Long getIdanimal() {
        return idanimal;
    }

    public void setIdanimal(Long idanimal) {
        this.idanimal = idanimal;
    }

    public String getAnimal() {
        return animal;
    }

    public void setAnimal(String animal) {
        this.animal = animal;
    }
 
 
 
}
