/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Interface.java to edit this template
 */
package com.avbravo.mongodbatlasdriver.repository;

import com.jmoordb.core.annotation.autosecuence.Autogenerated;
import com.jmoordb.core.annotation.enumerations.JakartaSource;
import com.jmoordb.core.model.Autosequence;
import com.jmoordb.core.annotation.autosecuence.AutosecuenceRepository;


/**
 *
 * @author avbravo
 */
@AutosecuenceRepository(entity = Autosequence.class, jakartaSource = JakartaSource.JAKARTA,
        database = "{mongodb.database}", collection = "autoincrementable")
public interface AutogeneratedRepository {

  @Autogenerated() 
  public Integer generate(String database,String collection);

}
