package com.avbravo.mongodbatlasdriver.repository;
// <editor-fold defaultstate="collapsed" desc="imports">

import com.avbravo.mongodbatlasdriver.repository.*;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.eclipse.microprofile.config.Config;
import org.eclipse.microprofile.config.inject.ConfigProperty;
/**
* MongoDB
*/
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.eq;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import org.bson.Document;
import com.mongodb.client.model.FindOneAndUpdateOptions;
import com.mongodb.client.model.ReturnDocument;
import com.mongodb.client.result.InsertOneResult;
import org.bson.BsonInt64;
import org.bson.conversions.Bson;
import org.bson.BsonDocument;
import com.mongodb.client.model.Filters;
import com.mongodb.client.result.UpdateResult;
/**
* Java
*/
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.Optional;
import java.util.function.Supplier;
import com.jmoordb.core.util.MessagesUtil;
import com.jmoordb.core.model.Pagination;
import com.jmoordb.core.model.Sorted;
import com.jmoordb.core.util.JmoordbCoreDateUtil;
import java.util.HashSet;
import com.avbravo.mongodbatlasdriver.model.Oceano;


// </editor-fold>
@ApplicationScoped
public class OceanoRepositoryImpl  implements OceanoRepository{
// <editor-fold defaultstate="collapsed" desc="inject">

    @Inject
    MongoClient mongoClient;
/**
* Microprofile Config
*/
    @Inject
    Config config;
    @Inject
    @ConfigProperty(name = "mongodb.database")
    String mongodbDatabase;

    String mongodbCollection = "oceano";
/**
* AutogeneratedRepository
*/
    @Inject
    com.avbravo.mongodbatlasdriver.repository.AutogeneratedRepository autogeneratedRepository;
/**
* Supplier
*/
    @Inject
    com.avbravo.mongodbatlasdriver.model.OceanoSupplier oceanoSupplier;
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="java.util.Optional<com.avbravo.mongodbatlasdriver.model.Oceano> findByIdoceano(java.lang.String idoceano ) ">

    @Override
    public java.util.Optional<com.avbravo.mongodbatlasdriver.model.Oceano> findByIdoceano(java.lang.String idoceano) {

        try {
               MongoDatabase database = mongoClient.getDatabase(mongodbDatabase);
               MongoCollection<Document> collection = database.getCollection(mongodbCollection);

               Bson filter =Filters.eq("idoceano",idoceano);

		Document doc = collection.find( filter )
					.first();

            Oceano oceano_ = oceanoSupplier.get(Oceano::new, doc);
            return Optional.of(oceano_);
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return Optional.empty();

     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc=" public Optional<Oceano> save(Oceano oceano)">

    @Override
    public Optional<Oceano> save(Oceano oceano) {
        try {
               MongoDatabase database = mongoClient.getDatabase(mongodbDatabase);
               MongoCollection<Document> collection = database.getCollection(mongodbCollection);
               
               if (findByPk(oceano.getIdoceano()).isPresent()) { 
                   MessagesUtil.warning("There is already a record with that id");
                  return Optional.of(oceano);
               }
               InsertOneResult insertOneResult = collection.insertOne(oceanoSupplier.toDocument(oceano));
               if (insertOneResult.getInsertedId() != null) {
                  return Optional.of(oceano);
               }
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return Optional.empty();
     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="Boolean update(Oceano oceano)">

    @Override
    public Boolean update(Oceano oceano) {
        try {
               MongoDatabase database = mongoClient.getDatabase(mongodbDatabase);
               MongoCollection<Document> collection = database.getCollection(mongodbCollection);
               if (!findByPk(oceano.getIdoceano()).isPresent()) { 
                   MessagesUtil.warning("Not found a record with that id");
                    return Boolean.FALSE;
               }
               Bson filter = Filters.empty();
               filter = Filters.eq("idoceano",oceano.getIdoceano());
               //Jsonb jsonb = JsonbBuilder.create();
               //UpdateResult result = collection.updateOne(filter, Document.parse(jsonb.toJson(oceano)));
               //UpdateResult result = collection.updateOne(filter, Document.parse(oceanoSupplier.toJson(oceano)));
               UpdateResult result = collection.updateOne(filter,oceanoSupplier.toDocument(oceano));
               if (result.getModifiedCount() > 0) {
                  return Boolean.TRUE;
               }
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return Boolean.FALSE;
     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="public List<Oceano> findAllPaginationSorted(Pagination pagination, Sorted sorted)">

    @Override
    public List<Oceano> findAllPaginationSorted(Pagination pagination, Sorted sorted) {
        List<Oceano> list = new ArrayList<>();
        try {
               MongoDatabase database = mongoClient.getDatabase(mongodbDatabase);
               MongoCollection<Document> collection = database.getCollection(mongodbCollection);
               MongoCursor<Document> cursor;
               		cursor = collection.find()
					.skip(pagination.skip())
			.limit(pagination.limit())
			.sort(sorted.getSort())
		.iterator();

               try{
                  while (cursor.hasNext()) {
                        list.add(oceanoSupplier.get(Oceano::new, cursor.next()));
                  }
               } finally {
                     cursor.close();
               } 
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return list;

     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="public List<Oceano> findAll()">

    @Override
    public List<Oceano> findAll() {
        List<Oceano> list = new ArrayList<>();
        try {
               MongoDatabase database = mongoClient.getDatabase(mongodbDatabase);
               MongoCollection<Document> collection = database.getCollection(mongodbCollection);
               MongoCursor<Document> cursor;
               		cursor = collection.find()
				.iterator();

               try{
                  while (cursor.hasNext()) {
                        list.add(oceanoSupplier.get(Oceano::new, cursor.next()));
                  }
               } finally {
                     cursor.close();
               } 
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return list;

     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="public List<Oceano> findAllPagination(Pagination pagination)">

    @Override
    public List<Oceano> findAllPagination(Pagination pagination) {
        List<Oceano> list = new ArrayList<>();
        try {
               MongoDatabase database = mongoClient.getDatabase(mongodbDatabase);
               MongoCollection<Document> collection = database.getCollection(mongodbCollection);
               MongoCursor<Document> cursor;
               		cursor = collection.find()
					.skip(pagination.skip())
			.limit(pagination.limit())
		.iterator();

               try{
                  while (cursor.hasNext()) {
                        list.add(oceanoSupplier.get(Oceano::new, cursor.next()));
                  }
               } finally {
                     cursor.close();
               } 
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return list;

     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="public List<Oceano> findAllSorted(Sorted sorted)">

    @Override
    public List<Oceano>  findAllSorted(Sorted sorted) {
        List<Oceano> list = new ArrayList<>();
        try {
               MongoDatabase database = mongoClient.getDatabase(mongodbDatabase);
               MongoCollection<Document> collection = database.getCollection(mongodbCollection);
               MongoCursor<Document> cursor;
               		cursor = collection.find()
					.sort(sorted.getSort())
		.iterator();

               try{
                  while (cursor.hasNext()) {
                        list.add(oceanoSupplier.get(Oceano::new, cursor.next()));
                  }
               } finally {
                     cursor.close();
               } 
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return list;

     }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="public Optional<Oceano> findByPk(String id )">

    public Optional<Oceano> findByPk(String id ) {
        try {
            MongoDatabase database = mongoClient.getDatabase(mongodbDatabase);
            MongoCollection<Document> collection = database.getCollection(mongodbCollection);
            Document doc = collection.find(eq("idoceano", id)).first();
            if(doc == null){
               return Optional.empty();
            }
            Oceano oceano = oceanoSupplier.get(Oceano::new, doc);
            return Optional.of(oceano);
       } catch (Exception e) {
            MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
       }
       return Optional.empty();
    }
// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="Long deleteByPK(String id )">

    @Override
    public Long deleteByPk(String id){
        try {
               MongoDatabase database = mongoClient.getDatabase(mongodbDatabase);
               MongoCollection<Document> collection = database.getCollection(mongodbCollection);
               MongoCursor<Document> cursor;
               Bson filter = Filters.eq("idoceano",id);

		com.mongodb.client.result.DeleteResult deleteResult = collection.deleteOne(filter);

               return deleteResult.getDeletedCount();
         } catch (Exception e) {
              MessagesUtil.error(MessagesUtil.nameOfClassAndMethod() + " " + e.getLocalizedMessage());
         }
         return 0L;
     }
// </editor-fold>

}