## YAML Template.
name: Build and test of Java Project
 
on: [push]
 
jobs:
 build:
   runs-on: ubuntu-latest
 
   steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt'
#     - name: Build with Maven
#       run: mvn -B package --file pom.xml payara-micro:bundle

     - run: mvn --batch-mode --update-snapshots verify payara-micro:bundle
     - run: mkdir staging && cp target/*.jar staging
     - uses: actions/upload-artifact@v2
       with:
           name: Package
           path: staging