
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM payara/micro:6.2023.10-jdk17

COPY target/capitulo11.war $DEPLOY_DIR

# CMD ["--nocluster","--deploymentDir", "/opt/payara/deployments", "--contextroot", "capitulo11"]