
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM payara/micro:6.2022.1

#COPY target/capitulo20.war $DEPLOY_DIR
COPY target/capitulo20.war $DEPLOY_DIR

