/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Interface.java to edit this template
 */
package org.acme.repository;

import com.jmoordb.core.annotation.autosecuence.Autogenerated;
import com.jmoordb.core.annotation.enumerations.JakartaSource;
import com.jmoordb.core.model.Autosequence;
import com.jmoordb.core.annotation.autosecuence.AutosecuenceRepository;


/**
 *
 * @author avbravo
 */
@AutosecuenceRepository(entity = Autosequence.class, jakartaSource = JakartaSource.JAVAEE_LEGACY,
        database = "{mongodb.database}", collection = "autosecuence")
public interface AutogeneratedRepository {

  @Autogenerated() 
  public Long generate(String database,String collection);

}
