kind: Service
apiVersion: v1
metadata:
  name: capitulo16
  labels:
    app: capitulo16
spec:
  type: NodePort
  selector:
    app: capitulo16
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: capitulo16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capitulo16
  template:
    metadata:
      labels:
        app: capitulo16
        version: v1
    spec:
      containers:
      - name: capitulo16
        image: capitulo16
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
